// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPNA5c3HbPa8UqYar4dGAjlFGY-BTrtBU',
    appId: '1:191168749897:web:9b1a5afb766959dc4ffa98',
    messagingSenderId: '191168749897',
    projectId: 'chatgram-app-f8c41',
    authDomain: 'chatgram-app-f8c41.firebaseapp.com',
    storageBucket: 'chatgram-app-f8c41.appspot.com',
    measurementId: 'G-KW2JK6ZBZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEVI58OLwweshpg5bUTuiUe_93AHckDyY',
    appId: '1:191168749897:android:9c3ec74a6b3eafec4ffa98',
    messagingSenderId: '191168749897',
    projectId: 'chatgram-app-f8c41',
    storageBucket: 'chatgram-app-f8c41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnn_msNRslJIl2KwXw15XyB36leBI0kao',
    appId: '1:191168749897:ios:c0eba69cadbb0d7f4ffa98',
    messagingSenderId: '191168749897',
    projectId: 'chatgram-app-f8c41',
    storageBucket: 'chatgram-app-f8c41.appspot.com',
    iosClientId: '191168749897-kglnumv69oqect655m3nvej7guekcfru.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
